apiVersion: v1
entries:
  dynatrace-operator:
  - apiVersion: v2
    appVersion: 0.0.1
    created: '2021-11-15T13:44:04.260449742Z'
    description: The Dynatrace Operator Helm chart for Kubernetes and OpenShift
    digest: fb0e82a1f72dcf6051dcbaa90519e41ba0ce4bc7385aaacba11537b5f07166ad
    home: https://www.dynatrace.com/
    icon: https://assets.dynatrace.com/global/resources/Signet_Logo_RGB_CP_512x512px.png
    maintainers:
    - email: marco.mader@dynatrace.com
      name: DTMad
    - email: michael.mayr@dynatrace.com
      name: mmayr-at
    name: dynatrace-operator
    sources:
    - https://github.com/Dynatrace/helm-charts
    type: application
    urls:
    - https://raw.githubusercontent.com/meik99/dynatrace-operator/master/config/helm/repos/stable/dynatrace-operator-0.0.1.tgz
    version: 0.0.1
generated: '2021-11-16T07:56:48.670202371Z'
